create table "public"."service_user" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "full_name" text,
    "supabase_user" uuid not null
);


alter table "public"."service_user" enable row level security;

create table "public"."tenet_permissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "service_user" bigint not null,
    "tenet" text not null
);


alter table "public"."tenet_permissions" enable row level security;

create table "public"."tenets" (
    "id" text not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "domain" text not null
);


alter table "public"."tenets" enable row level security;

CREATE UNIQUE INDEX service_user_pkey ON public.service_user USING btree (id);

CREATE UNIQUE INDEX tenet_permissions_pkey ON public.tenet_permissions USING btree (id);

CREATE UNIQUE INDEX tenets_domain_key ON public.tenets USING btree (domain);

CREATE UNIQUE INDEX tenets_pkey ON public.tenets USING btree (id);

alter table "public"."service_user" add constraint "service_user_pkey" PRIMARY KEY using index "service_user_pkey";

alter table "public"."tenet_permissions" add constraint "tenet_permissions_pkey" PRIMARY KEY using index "tenet_permissions_pkey";

alter table "public"."tenets" add constraint "tenets_pkey" PRIMARY KEY using index "tenets_pkey";

alter table "public"."service_user" add constraint "service_user_supabase_user_fkey" FOREIGN KEY (supabase_user) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."service_user" validate constraint "service_user_supabase_user_fkey";

alter table "public"."tenet_permissions" add constraint "tenet_permissions_service_user_fkey" FOREIGN KEY (service_user) REFERENCES service_user(id) not valid;

alter table "public"."tenet_permissions" validate constraint "tenet_permissions_service_user_fkey";

alter table "public"."tenet_permissions" add constraint "tenet_permissions_tenet_fkey" FOREIGN KEY (tenet) REFERENCES tenets(id) not valid;

alter table "public"."tenet_permissions" validate constraint "tenet_permissions_tenet_fkey";

alter table "public"."tenets" add constraint "tenets_domain_key" UNIQUE using index "tenets_domain_key";

grant delete on table "public"."service_user" to "anon";

grant insert on table "public"."service_user" to "anon";

grant references on table "public"."service_user" to "anon";

grant select on table "public"."service_user" to "anon";

grant trigger on table "public"."service_user" to "anon";

grant truncate on table "public"."service_user" to "anon";

grant update on table "public"."service_user" to "anon";

grant delete on table "public"."service_user" to "authenticated";

grant insert on table "public"."service_user" to "authenticated";

grant references on table "public"."service_user" to "authenticated";

grant select on table "public"."service_user" to "authenticated";

grant trigger on table "public"."service_user" to "authenticated";

grant truncate on table "public"."service_user" to "authenticated";

grant update on table "public"."service_user" to "authenticated";

grant delete on table "public"."service_user" to "service_role";

grant insert on table "public"."service_user" to "service_role";

grant references on table "public"."service_user" to "service_role";

grant select on table "public"."service_user" to "service_role";

grant trigger on table "public"."service_user" to "service_role";

grant truncate on table "public"."service_user" to "service_role";

grant update on table "public"."service_user" to "service_role";

grant delete on table "public"."tenet_permissions" to "anon";

grant insert on table "public"."tenet_permissions" to "anon";

grant references on table "public"."tenet_permissions" to "anon";

grant select on table "public"."tenet_permissions" to "anon";

grant trigger on table "public"."tenet_permissions" to "anon";

grant truncate on table "public"."tenet_permissions" to "anon";

grant update on table "public"."tenet_permissions" to "anon";

grant delete on table "public"."tenet_permissions" to "authenticated";

grant insert on table "public"."tenet_permissions" to "authenticated";

grant references on table "public"."tenet_permissions" to "authenticated";

grant select on table "public"."tenet_permissions" to "authenticated";

grant trigger on table "public"."tenet_permissions" to "authenticated";

grant truncate on table "public"."tenet_permissions" to "authenticated";

grant update on table "public"."tenet_permissions" to "authenticated";

grant delete on table "public"."tenet_permissions" to "service_role";

grant insert on table "public"."tenet_permissions" to "service_role";

grant references on table "public"."tenet_permissions" to "service_role";

grant select on table "public"."tenet_permissions" to "service_role";

grant trigger on table "public"."tenet_permissions" to "service_role";

grant truncate on table "public"."tenet_permissions" to "service_role";

grant update on table "public"."tenet_permissions" to "service_role";

grant delete on table "public"."tenets" to "anon";

grant insert on table "public"."tenets" to "anon";

grant references on table "public"."tenets" to "anon";

grant select on table "public"."tenets" to "anon";

grant trigger on table "public"."tenets" to "anon";

grant truncate on table "public"."tenets" to "anon";

grant update on table "public"."tenets" to "anon";

grant delete on table "public"."tenets" to "authenticated";

grant insert on table "public"."tenets" to "authenticated";

grant references on table "public"."tenets" to "authenticated";

grant select on table "public"."tenets" to "authenticated";

grant trigger on table "public"."tenets" to "authenticated";

grant truncate on table "public"."tenets" to "authenticated";

grant update on table "public"."tenets" to "authenticated";

grant delete on table "public"."tenets" to "service_role";

grant insert on table "public"."tenets" to "service_role";

grant references on table "public"."tenets" to "service_role";

grant select on table "public"."tenets" to "service_role";

grant trigger on table "public"."tenets" to "service_role";

grant truncate on table "public"."tenets" to "service_role";

grant update on table "public"."tenets" to "service_role";


